Allow for multiple markers per track
lavalink-devs/lavaplayer pull request #56
Opened 2023-12-27 18:55 UTC by duncte123

WARNING: this has not been tested yet

2023-12-27 19:02 UTC, duncte123 commented
I'm not yet sure what to do with the remove method, but that's a worry for tomorrow

2023-12-27 21:31 UTC, devoxin requested changes

2023-12-27 21:31 UTC, devoxin commented on main/src/main/java/com/sedmelluq/discord/lavaplayer/track/TrackMarkerTracker.java
>      public void trigger(TrackMarkerHandler.MarkerState state) {
This function needs its documentation updating to state that all registered markers will be triggered with the provided state

2023-12-27 21:31 UTC, devoxin commented on main/src/main/java/com/sedmelluq/discord/lavaplayer/track/TrackMarkerTracker.java
> +                trigger(marker, LATE);
Perhaps avoid storing the marker if the timecode has already been surpassed

2023-12-27 21:31 UTC, devoxin commented on main/src/main/java/com/sedmelluq/discord/lavaplayer/track/playback/AudioTrackExecutor.java
> +     * Set track position marker. Overrides all current markers.
```suggestion
     * Set the track position marker. This will clear all existing markers.
```

2023-12-28 08:27 UTC, duncte123 commented on main/src/main/java/com/sedmelluq/discord/lavaplayer/track/TrackMarkerTracker.java
> +        markerList.forEach(this::remove);
Maybe it's better to trigger overwritten here the marker is not null?

2023-12-28 16:07 UTC, devoxin approved these changes
LGTM

2023-12-28 16:07 UTC, merged